### ISSUE TITLE
覆盖上传方式，不能成功

### ISSUE THREAD

**Issue by yingye** [Jeff2Ma/gulp-qcloud-upload#2]
![image](https://user-images.githubusercontent.com/19258729/28264848-69279494-6b1f-11e7-8f33-cbe5376c67e4.png)

**Comment by Jeff2Ma** [comment]
恩，这种情况其实我也遇到过，一般发生在你文件已经在 cos 的bucket 里面但之前是用其它方式上传的。如果你的文件第一次上传也是用这个插件的，再次上传就没有问题。

**Comment by yingye** [comment]
不，第一次就是使用这个方式上传的

**Comment by Jeff2Ma** [comment]
你好，我昨晚拿自己的账号重新配置用了下是正常的，排除了官方修改 api 的可能。可否借助 https://www.qcloud.com/document/product/436/7730 排查下问题？
